//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.ShiftContext.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HR.ShiftContext.Resources.ExceptionResource", typeof(ExceptionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dfdf.
        /// </summary>
        public static string EmployeeDontHaveShiftAssignmentException {
            get {
                return ResourceManager.GetString("EmployeeDontHaveShiftAssignmentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای شیفت های ثابت  این امکان وجود ندارد.
        /// </summary>
        public static string InvalidInOrderSingleShiftSegmentException {
            get {
                return ResourceManager.GetString("InvalidInOrderSingleShiftSegmentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت شروع شیفت باید کوچک تر از ساعت پایان شیفت باشد.
        /// </summary>
        public static string InvalidShiftTimeRangeException {
            get {
                return ResourceManager.GetString("InvalidShiftTimeRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت شروع شیفت بعدی مطابقت ندارد.
        /// </summary>
        public static string MissMatchNextShiftStartTimeException {
            get {
                return ResourceManager.GetString("MissMatchNextShiftStartTimeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه شیفت معتبر نمی باشد.
        /// </summary>
        public static string NextShiftNotExistsException {
            get {
                return ResourceManager.GetString("NextShiftNotExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه شیف بعدی نمی تواند شناسه شیف فعلی باشد.
        /// </summary>
        public static string NextShiftRecursiveException {
            get {
                return ResourceManager.GetString("NextShiftRecursiveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شیفت بعدی قبلا رزرو شده.
        /// </summary>
        public static string NextShiftReservedException {
            get {
                return ResourceManager.GetString("NextShiftReservedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در شیفت های متوالی غیر تعطیل، ساعت شروع شیفت بعدی باید بزرگتر از ساعت پایان شیفت قبلی آن باشد..
        /// </summary>
        public static string NextShiftSegmentStartTimeGreaterThanShiftSegmentEndTimeException {
            get {
                return ResourceManager.GetString("NextShiftSegmentStartTimeGreaterThanShiftSegmentEndTimeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد الگوی شیفت بعدی مغایرت دارد.
        /// </summary>
        public static string NextShiftTemplateIdConflictException {
            get {
                return ResourceManager.GetString("NextShiftTemplateIdConflictException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الگوی شیفت نامعتبر است.
        /// </summary>
        public static string ShiftExistsException {
            get {
                return ResourceManager.GetString("ShiftExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد الگوی شیفت الزامی است.
        /// </summary>
        public static string ShiftIdRequiredException {
            get {
                return ResourceManager.GetString("ShiftIdRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه شیف بعدی نمی تواند شناسه شیف فعلی باشد.
        /// </summary>
        public static string ShiftSegmentInOrderInvalidSelfRefrenceException {
            get {
                return ResourceManager.GetString("ShiftSegmentInOrderInvalidSelfRefrenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شیفت های با الگوی شیفت یکسان می توانند به یکدیگر ارتباط داده شوند.
        /// </summary>
        public static string ShiftSegmentInOrderToAnotherShiftException {
            get {
                return ResourceManager.GetString("ShiftSegmentInOrderToAnotherShiftException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد الگوی شیفت الزامی است.
        /// </summary>
        public static string ShiftTemplateIdRequiredException {
            get {
                return ResourceManager.GetString("ShiftTemplateIdRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان الگوی شیفت الزامی است.
        /// </summary>
        public static string ShiftTemplateTitleRequiredException {
            get {
                return ResourceManager.GetString("ShiftTemplateTitleRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازه ساعتی شیفت تعریف نشده است.
        /// </summary>
        public static string ShiftTimeRequiredException {
            get {
                return ResourceManager.GetString("ShiftTimeRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان شیفت الزامی است.
        /// </summary>
        public static string ShiftTitleRequiredException {
            get {
                return ResourceManager.GetString("ShiftTitleRequiredException", resourceCulture);
            }
        }
    }
}
